parameters:
  - name: TerraformVariableFiles
    type: object
    default: { }
    displayName: ''

jobs:
  - job:
    variables:
      - name: varFiles
        value: '${{ each file in parameters.TerraformVariableFiles }} -var-file="${{ file }}"${{ end }}'
    steps:
      - script: echo $(varFiles)
