parameters:
  - name: TerraformVariableFiles
    type: object
    default: { }
    displayName: ''

jobs:
  - job:
    variables:
      TF_VAR_ARGS: >
        ${{ join(parameters.TerraformVariableFiles, '" -var-file="') }}
    steps:
      - script: echo $(TF_VAR_ARGS)
