parameters:
  - name: TerraformVariableFiles
    type: object
    default: { }
    displayName: ''

jobs:
  - job:
    variables:
      TF_VAR_ARGS: >
        ${{ join(parameters.tfVarFiles, '" -var-file="')) }}
    steps:
      - script: echo $(varFiles)
