parameters:
  - name: TerraformVariableFiles
    type: object
    default: { }
    displayName: ''

  - name: myArray
    type: object
    default:
      - FOO
      - BAR
      - ZOO

jobs:
  - job:
    variables:
      TF_VAR_ARGS: ${{ join('" -var-file="', parameters.TerraformVariableFiles) }}
      A: ${{ join(';',parameters.myArray) }}
    steps:
      - script: echo $(TF_VAR_ARGS)
      - script: echo $(A)
