parameters:
  - name: TerraformVariableFiles
    type: object
    default: { }
    displayName: ''

  - name: myArray
    type: object
    default:
      - FOO
      - BAR
      - ZOO

jobs:
  - job:
    variables:
      - template: ConcatList.yml
        parameters:
          Items: ${{ parameters.TerraformVariableFiles }}
          Prefix: ' -var-file="'
          Suffix: '"'
          OutputVariableName: TF_VAR_VIA_TEMPLATE
      - name: TF_VAR_ARGS_SHARD
        value: ${{ join('" -var-file="', parameters.TerraformVariableFiles) }}
      - name: TF_VAR_ARGS
        value: ' -var-file="${{ variables.TF_VAR_ARGS_SHARD }}"'
      - name: A
        value: ${{ join(';',parameters.myArray) }}
    steps:
      - script: echo $(TF_VAR_ARGS)
      - script: echo $(A)
      - script: echo $(TF_VAR_VIA_TEMPLATE)
