# Azure DevOps Task: TerraformInstaller@1
#
# Purpose:
#   Installs a specific version of the Terraform CLI in an Azure DevOps pipeline, enabling infrastructure-as-code workflows.
#
# Parameters:
#   - TerraformVersion (string, optional): The version of Terraform CLI to install.
#     Must be 'latest' or a strict semantic version (e.g., '1.11.3'). Wildcards like '1.11.x' are not accepted.
#     Default: '1.14.0'
#
# Example Usage:
#   - template: tasks/terraform_installer.yml
#     parameters:
#       TerraformVersion: '1.3.5'
#
# Notes:
#   - Uses the TerraformInstaller@1 task from Microsoft DevLabs.
#   - Ensure the specified version is compatible with your pipeline and Terraform code.
#   - See: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks

parameters:
  - name: TerraformVersion
    type: string
    default: '1.14.0'
    displayName: 'Terraform CLI version to install'

steps:
  - ${{ if and(ne(parameters.TerraformVersion, 'latest'), lt(replace(parameters.TerraformVersion, '.', ''), 1)) }}: # lt will raise conversion error if the version isn't a number
      - "'terraform_installer' task error: TerraformVersion is not properly defined. Must either be 'latest' or semantic version 'x.y.z'.": "Error"
  - task: TerraformInstaller@1
    displayName: 'Install Terraform CLI: ${{ parameters.TerraformVersion }}'
    name: TerraformInstall
    inputs:
      terraformVersion: ${{ parameters.TerraformVersion }}
