parameters:
  - name: PipelinePool
    type: string
    default: 'Mare Nectaris'
    displayName: 'The pool that the pipeline will run from the highest level'

  - name: RelativePathToTerraformFiles
    type: string
    default: ''
    displayName: 'Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact'

  - name: TerraformVersion
    type: string
    default: 'latest'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformBuildInjectionSteps
    type: stepList
    default: []
    displayName: 'Steps to be carried out before the terraform is init, validated, and packaged'

  - name: AzDOEnvironmentName
    type: string
    default: ''
    displayName: 'AzDO Environment name to associate the deployment jobs too'

  - name: AzureSubscriptionServiceConnection
    type: string
    default: ''
    displayName: 'Azure service connection for the azdo environment'

  - name: DeploymentJobsVariableMappings
    type: object
    default: { }
    displayName: 'Variable mappings to be associated with the deployment jobs.'

  # terraform init task parameters

  - name: BackendAzureServiceConnection
    type: string
    default: ''
    displayName: 'Azure service connection for backend where the state is stored'

  - name: BackendAzureStorageAccountName
    type: string
    default: ''
    displayName: 'Azure storage account name for backend where the state is stored'

  - name: BackendAzureContainerName
    type: string
    default: ''
    displayName: 'Azure storage container name for backend where the state is stored'

  - name: BackendAzureBlobName
    type: string
    default: ''
    displayName: 'Azure storage blob name for backend where the state is stored'

  - name: BackendAzureStorageAccountResourceGroupName
    type: string
    default: ''
    displayName: 'Azure resource group name for backend where the state is stored'

# Key Vault Parameters

  - name: KeyVaultServiceConnection
    type: string
    default: ''
    displayName: 'Service connection for key vault access secrets'

  - name: KeyVaultName
    type: string
    default: ''
    displayName: 'Name of key vault for accessing secrets'

  - name: KeyVaultSecretsFilter
    type: string
    default: '*'
    displayName: 'Filter for secrets to access from key vault'

  - name: RunPlanOnly
    type: boolean
    default: false
    displayName: 'Whether only the terraform plan should be ran and no deployment made'

variables:
  - name: PipelinePool
    value: ${{ parameters.PipelinePool }}

stages:
  - template: ../stages/terraform_build.yml
    parameters:
      RelativePathToTerraformFiles: ${{ parameters.RelativePathToTerraformFiles }}
      TerraformVersion: ${{ parameters.TerraformVersion }}
      TerraformBuildInjectionSteps: ${{ parameters.TerraformBuildInjectionSteps }}

  - template: ../stages/terraform_deploy.yml
    parameters:
      DependsOn:
        - Build
      Condition: succeeded('Build')
      AzureSubscriptionServiceConnection: ${{ parameters.AzureSubscriptionServiceConnection }}
      AzDOEnvironmentName: ${{ parameters.AzDOEnvironmentName }}
      TerraformVersion: ${{ parameters.TerraformVersion }}
      TerraformJobVariableMappings: ${{ parameters.DeploymentJobsVariableMappings }}
      BackendAzureServiceConnection: ${{ parameters.BackendAzureServiceConnection }}
      BackendAzureStorageAccountResourceGroupName: ${{ parameters.BackendAzureStorageAccountResourceGroupName }}
      BackendAzureStorageAccountName: ${{ parameters.BackendAzureStorageAccountName }}
      BackendAzureContainerName: ${{ parameters.BackendAzureContainerName }}
      BackendAzureBlobName: ${{ parameters.BackendAzureBlobName }}
      KeyVaultServiceConnection: ${{ parameters.KeyVaultServiceConnection }}
      KeyVaultName: ${{ parameters.KeyVaultName }}
      KeyVaultSecretsFilter: ${{ parameters.KeyVaultSecretsFilter }}
      RunPlanOnly: ${{ parameters.RunPlanOnly }}
      # TerraformVariableMappings: # todo
      # TerraformOutputVariables: # todo
      # TerraformVariableFiles: # todo
