parameters:
  - name: PipelinePool
    type: string
    default: 'Mare Nectaris'
    displayName: 'The pool that the pipeline will run from the highest level'

  - name: RelativePathToTerraformFiles
    type: string
    default: ''
    displayName: 'Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact'

  - name: TerraformVersion
    type: string
    default: '1.14.x'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformBuildInjectionSteps
    type: stepList
    default: [ ]
    displayName: 'Steps to be carried out before the terraform is init, validated, and packaged'

  - name: RunPlanOnly
    type: boolean
    default: false
    displayName: 'Whether only the terraform plan should be ran and no deployment made'

  - name: Environments
    type: object
    displayName: 'Mapping of environments'

variables:
  - name: PipelinePool
    value: ${{ parameters.PipelinePool }}

stages:
  - template: ../stages/terraform_build.yml
    parameters:
      RelativePathToTerraformFiles: ${{ parameters.RelativePathToTerraformFiles }}
      TerraformVersion: ${{ parameters.TerraformVersion }}
      TerraformBuildInjectionSteps: ${{ parameters.TerraformBuildInjectionSteps }}

  - ${{ each environment in parameters.Environments }}:
      - template: ../stages/terraform_deploy.yml
        parameters:
          ${{ if or(not(parameters.Environment.Name), eq(parameters.Environment.Name, '')) }}:
            "an environment name is not properly defined and is a required field.": "Error"
          TerraformVersion: ${{ parameters.TerraformVersion }}
          RunPlanOnly: ${{ parameters.RunPlanOnly }}
          Environment: ${{ environment }}

