parameters:
  - name: PipelinePool
    type: string
    default: "Mare Nectaris"
    displayName: "The pool that the pipeline will run from the highest level."

  - name: RelativePathToTerraformFiles
    type: string
    displayName: "Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact."

pool: ${{ variables.PipelinePool }}

stages:
  - template: ../stages/terraform_build.yml
    parameters:
      RelativePathToTerraformFiles: ${{ parameters.RelativePathToTerraformFiles }}
