parameters:
  - name: ArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Artifact Name for Target Path to be saved as.'

  - name: RelativePathToTerraformFiles
    type: string
    default: ''
    displayName: "Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact."

  - name: TerraformVersion
    type: string
    default: 'latest'
    displayName: "Version of Terraform CLI tool to use with the terraform files."

jobs:
  - job: TerraformBuild
    variables:
      TargetPath: $(Build.SourcesDirectory)/${{ parameters.RelativePathToTerraformFiles }}
    workspace:
      clean: all
    displayName: "Terraform Build"
    steps:
      - checkout: self
        displayName: "Checkout self repository"

      - template: ../tasks/terraform_installer.yml
        parameters:
          TerraformVersion: ${{ parameters.TerraformVersion }}

      - template: ../tasks/terraform.yml
        parameters:
          Command: init
          DisableBackend: true
          WorkingDirectory: ${{ variables.TargetPath }}

      - template: ../tasks/terraform.yml
        parameters:
          Command: validate
          WorkingDirectory: ${{ variables.TargetPath }}

      - checkout: self
        displayName: "Clean the directory post validation"
        clean: true

      - template: ../tasks/publish_pipeline_artifact.yml
        parameters:
          TargetPath: ${{ variables.TargetPath }}
          ArtifactName: ${{ parameters.ArtifactName }}
