parameters:
  - name: ArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Artifact Name for Target Path to be saved as'

  - name: RelativePathToTerraformFiles
    type: string
    default: ''
    displayName: 'Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact'

  - name: AdditionalFilesToPackage
    type: object
    default: [ ]
    displayName: 'List of additional files to include in the terraform artifact (SourceDirectory, FilesPattern, TargetSubdirectoryName)'

  - name: TerraformVersion
    type: string
    default: '1.14.0'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformBuildInjectionSteps
    type: stepList
    default: [ ]
    displayName: 'Steps to be carried out before the terraform is init, validated, and packaged'

jobs:
  - job: TerraformBuild
    displayName: 'Terraform Build'
    variables:
      RepositoryCheckoutFolderName: $(Build.Repository.Name)
      RepositoryDirectory: $(Pipeline.Workspace)/$(RepositoryCheckoutFolderName)
      TerraformWorkingDirectory: $(RepositoryDirectory)/${{ parameters.RelativePathToTerraformFiles }}
    workspace:
      clean: all
    steps:
      - template: /jobs/terraform_repository_checkout_stepsList.yml
        parameters:
          AdditionalFilesToPackage: ${{ parameters.AdditionalFilesToPackage }}
          TerraformBuildInjectionSteps: ${{ parameters.TerraformBuildInjectionSteps }}

      - template: /tasks/terraform_installer.yml
        parameters:
          TerraformVersion: ${{ parameters.TerraformVersion }}

      - template: /tasks/terraform.yml
        parameters:
          Command: init
          CommandOptions: '-backend=false'
          WorkingDirectory: $(TerraformWorkingDirectory)

      - template: /tasks/terraform.yml
        parameters:
          Command: validate
          WorkingDirectory: $(TerraformWorkingDirectory)

      - template: /jobs/terraform_repository_checkout_stepsList.yml
        parameters:
          AdditionalFilesToPackage: ${{ parameters.AdditionalFilesToPackage }}
          TerraformBuildInjectionSteps: ${{ parameters.TerraformBuildInjectionSteps }}

      - template: /tasks/publish_pipeline_artifact.yml
        parameters:
          TargetPath: $(TerraformWorkingDirectory)
          ArtifactName: ${{ parameters.ArtifactName }}
