# Job Template: Terraform deploy
# Purpose: Runs Terraform deploy infrastructure, supporting variable injection and Azure Key Vault integration.

parameters:
  # generic parameters
  - name: TerraformDeployMode
    type: string
    default: Plan
    values:
      - Apply
      - Plan
    displayName: 'The terraform deploy mode: plan or apply'

  - name: DependsOn
    type: object
    default: [ ]
    displayName: 'List of jobs this job depends on'

  - name: Condition
    type: string
    default: succeeded()
    displayName: 'The condition that will control whether this job runs or not'

  - name: TerraformVersion
    type: string
    default: '1.14.x'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Name for the artifact containing the terraform files for deployment'

  - name: EnvironmentName
    type: string
    # no default:
    displayName: ''

  - name: InfrastructureConfig
    type: object
    # NO default - Consumer must provide this
    displayName: |
      The configuration for the target environment to deploy terraform to. Definition

      REQUIRED PROPERTIES:

      AzureSubscriptionServiceConnection: string # The Azure DevOps service connection name used to authenticate with Azure.
      AzDOEnvironmentName: string # The Azure DevOps environment name for approval gates and deployment tracking.
      BackendConfig: object # Configuration for Terraform backend state storage in Azure.
        ServiceConnection: string # Azure service connection for backend access
        ResourceGroupName: string # Resource group containing the storage account
        StorageAccountName: string # Storage account name for Terraform state
        ContainerName: string # Container name within the storage account
        BlobName: string # Blob name for the Terraform state file
      VerificationMode: string # Controls when manual verification is required. Must be one of:
        'VerifyOnDestroy' # Verify only on infrastructure destruction
        'VerifyOnAny' # Verify on any infrastructure change
        'VerifyDisabled' # No manual verification required

      OPTIONAL PROPERTIES:

      KeyVaultConfig: object # (all-or-nothing - if any property is set, all must be set) configuration for retrieving secrets from Azure Key Vault.
        ServiceConnection: string # Azure service connection for Key Vault access
        Name: string # Key Vault name
        SecretsFilter: string # Filter for secrets to retrieve (e.g., '*' for all)
      JobsVariableMappings: object # List of variable mappings (variable groups, templates, or inline variables).
        Can include:
          - Variable groups: { group: 'GroupName' }
          - Templates: { template: 'path/to/template.yml' }
          - Inline variables: { name: 'VarName', value: 'VarValue' }
      EnvironmentVariableMappings: object # Key-value pairs of environment variables to set for Terraform execution.
      VariableFiles: list of strings # List of Terraform variable file paths (e.g., ['config/common.tfvars', 'config/dev.tfvars']).
      OutputVariables: list of strings # List of Terraform output variable names to export as pipeline variables.

      EXAMPLE:

      InfrastructureConfig:
      - AzureSubscriptionServiceConnection: AzureServiceConnection-Production
        AzDOEnvironmentName: production-environment
        BackendConfig:
          ServiceConnection: AzureServiceConnection-TerraformState
          ResourceGroupName: rg-terraform-state-prod
          StorageAccountName: sttfstateprod
          ContainerName: tfstate
          BlobName: production.terraform.tfstate
        VerificationMode: VerifyOnAny
        KeyVaultConfig:
          ServiceConnection: AzureServiceConnection-Production
          Name: kv-production-secrets
          SecretsFilter: '*'
        JobsVariableMappings:
          - group: ProductionVariableGroup
          - group: CommonVariableGroup
          - template: config/production-variables.yml
          - name: ENVIRONMENT_NAME
            value: production
          - name: LOG_LEVEL
            value: info
        EnvironmentVariableMappings:
          TF_LOG: INFO
          ARM_SKIP_PROVIDER_REGISTRATION: 'true'
        VariableFiles:
          - config/common.tfvars
          - config/production.tfvars
        OutputVariables:
          - resource_group_name
          - app_service_url
          - storage_account_name
jobs:
  - deployment: TerraformDeploy_${{ parameters.TerraformDeployMode }}
    displayName: 'Terraform ${{ parameters.TerraformDeployMode }}'

    ${{ if or(not(parameters.InfrastructureConfig.AzureSubscriptionServiceConnection), eq(parameters.InfrastructureConfig.AzureSubscriptionServiceConnection, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: AzureSubscriptionServiceConnection is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.AzDOEnvironmentName), eq(parameters.InfrastructureConfig.AzDOEnvironmentName, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: AzDOEnvironmentName is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.BackendConfig.ServiceConnection), eq(parameters.InfrastructureConfig.BackendConfig.ServiceConnection, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: BackendConfig.ServiceConnection is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.BackendConfig.ResourceGroupName), eq(parameters.InfrastructureConfig.BackendConfig.ResourceGroupName, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: BackendConfig.ResourceGroupName is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.BackendConfig.StorageAccountName), eq(parameters.InfrastructureConfig.BackendConfig.StorageAccountName, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: BackendConfig.StorageAccountName is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.BackendConfig.ContainerName), eq(parameters.InfrastructureConfig.BackendConfig.ContainerName, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: BackendConfig.ContainerName is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.BackendConfig.BlobName), eq(parameters.InfrastructureConfig.BackendConfig.BlobName, '')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: BackendConfig.BlobName is not properly defined and is a required field.": "Error"

    ${{ if or(not(parameters.InfrastructureConfig.VerificationMode), eq(parameters.InfrastructureConfig.VerificationMode, ''), notIn(parameters.InfrastructureConfig.VerificationMode, 'VerifyOnDestroy', 'VerifyOnAny', 'VerifyDisabled')) }}:
      "'${{ parameters.EnvironmentName }}' environment error: VerificationMode is not properly defined and is a required field.": "Error"

    # OPTIONAL PARAMETERS

    ${{ if or(parameters.InfrastructureConfig.KeyVaultConfig.ServiceConnection, parameters.InfrastructureConfig.KeyVaultConfig.Name, parameters.InfrastructureConfig.KeyVaultConfig.SecretsFilter) }}:
      # At least one property is set, so all three must be set
      ${{ if or(not(parameters.InfrastructureConfig.KeyVaultConfig.ServiceConnection), eq(parameters.InfrastructureConfig.KeyVaultConfig.ServiceConnection, '')) }}:
        "'${{ parameters.EnvironmentName }}' environment error: KeyVaultConfig.ServiceConnection is required when any Key Vault configuration is provided.": "Error"
      ${{ if or(not(parameters.InfrastructureConfig.KeyVaultConfig.Name), eq(parameters.InfrastructureConfig.KeyVaultConfig.Name, '')) }}:
        "'${{ parameters.EnvironmentName }}' environment error: KeyVaultConfig.Name is required when any Key Vault configuration is provided.": "Error"
      ${{ if or(not(parameters.InfrastructureConfig.KeyVaultConfig.SecretsFilter), eq(parameters.InfrastructureConfig.KeyVaultConfig.SecretsFilter, '')) }}:
        "'${{ parameters.EnvironmentName }}' environment error: KeyVaultConfig.SecretsFilter is required when any Key Vault configuration is provided.": "Error"

    ${{ if parameters.InfrastructureConfig.EnvironmentVariableMappings }}:
      ${{ if not(contains(convertToJson(parameters.InfrastructureConfig.EnvironmentVariableMappings), '{')) }}:
        "'${{ parameters.EnvironmentName }}' environment error: EnvironmentVariableMappings is not correct. Must be an object of key/value pairs. You muppet.": "Error"
      ${{ else }}:
        ${{ each mapping in parameters.InfrastructureConfig.EnvironmentVariableMappings }}:
          ${{ if or(not(mapping.Key), not(mapping.Value), eq(mapping.Key, ''), eq(mapping.Value, '')) }}:
            "'${{ parameters.EnvironmentName }}' environment error: EnvironmentVariableMappings is not correct. Must be an object of key/value pairs. You muppet.": "Error"

    ${{ if parameters.InfrastructureConfig.VariableFiles }}: # Only run validation if the optional parameter is present
      ${{ if not(contains(convertToJson(parameters.InfrastructureConfig.VariableFiles), '[')) }}: # Make sure it is a list
        "'${{ parameters.EnvironmentName }}' environment error: VariableFiles is not correct. Must be a list of string values. You muppet.": "Error"
      ${{ else }}:
        ${{ each variable in parameters.InfrastructureConfig.VariableFiles }}: # Make sure each item in the list is just a string
          ${{ if or(contains(convertToJson(variable), '['), contains(convertToJson(variable), '{')) }}: # if either is present, it is an object not a string
            "'${{ parameters.EnvironmentName }}' environment error: VariableFiles item '${{ replace(convertToJson(variable), '\n', ' ') }}' is not a string. This parameter be a list of string values. You muppet.": "Error"

    ${{ if parameters.InfrastructureConfig.OutputVariables }}: # Only run validation if the optional parameter is present
      ${{ if not(contains(convertToJson(parameters.InfrastructureConfig.OutputVariables), '[')) }}: # Make sure it is a list
        "'${{ parameters.EnvironmentName }}' environment error: OutputVariables is not correct. Must be a list of string values. You muppet.": "Error"
      ${{ else }}:
        ${{ each variable in parameters.InfrastructureConfig.OutputVariables }}: # Make sure each item in the list is just a string
          ${{ if or(contains(convertToJson(variable), '['), contains(convertToJson(variable), '{')) }}: # if either is present, it is an object not a string
            "'${{ parameters.EnvironmentName }}' environment error: OutputVariables item '${{ replace(convertToJson(variable), '\n', ' ') }}' is not a string. This parameter be a list of string values. You muppet.": "Error"

    environment: ${{ parameters.InfrastructureConfig.AzDOEnvironmentName }}
    condition: ${{ parameters.Condition }}
    dependsOn: ${{ parameters.DependsOn }}
    variables:
      # Terraform Plan Variables
      - ${{ if eq(parameters.TerraformDeployMode, 'Plan') }}:
          - name: TerraformPlanFilePath
            value: $(TerraformWorkingDirectory)/tfplan

      # Terraform Apply Variables
      - ${{ if eq(parameters.TerraformDeployMode, 'Apply') }}:
          - name: TerraformOutputVariablesCommandOption
            value: ${{ join(',', parameters.InfrastructureConfig.OutputVariables) }}

      # Shared Variables
      - template: ../utils/concat_wrap_list.yml
        parameters:
          Items: ${{ parameters.InfrastructureConfig.VariableFiles }}
          Prefix: ' -var-file="$(TerraformWorkingDirectory)/'
          Suffix: '"'
          OutputVariableName: VariableFilesCommandOption
      - name: TerraformWorkingDirectory
        value: $(Pipeline.Workspace)/${{ parameters.TerraformArtifactName }}
      - name: CheckoutPath
        value: devops-azdo-yaml-pipeline-templates
      - name: ScriptDirectory
        value: $(Pipeline.Workspace)/$(CheckoutPath)/scripts

      - ${{ if parameters.InfrastructureConfig.JobsVariableMappings }}: # Only run validation if the optional parameter is present
        - ${{ parameters.InfrastructureConfig.JobsVariableMappings }} # Consumer Input Variables (can override the above)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: AzDOPipelineTemplates
              persistCredentials: true
              path: $(CheckoutPath)

            - template: ../tasks/download_pipeline_artifact.yml
              parameters:
                ArtifactName: ${{ parameters.TerraformArtifactName }}

            - template: ../tasks/terraform_installer.yml
              parameters:
                TerraformVersion: ${{ parameters.TerraformVersion }}

            - ${{ if and(parameters.InfrastructureConfig.KeyVaultServiceConnection, parameters.InfrastructureConfig.KeyVaultName, parameters.InfrastructureConfig.KeyVaultSecretsFilter) }}:
                - template: ../tasks/azure_key_vault.yml
                  parameters:
                    KeyVaultServiceConnection: ${{ parameters.InfrastructureConfig.KeyVaultServiceConnection }}
                    KeyVaultName: ${{ parameters.InfrastructureConfig.KeyVaultName }}
                    SecretsFilter: ${{ parameters.InfrastructureConfig.KeyVaultSecretsFilter }}

            - template: ../tasks/terraform.yml
              parameters:
                Command: init
                BackendAzureServiceConnection: ${{ parameters.InfrastructureConfig.BackendConfig.ServiceConnection }}
                BackendAzureResourceGroupName: ${{ parameters.InfrastructureConfig.BackendConfig.ResourceGroupName }}
                BackendAzureStorageAccountName: ${{ parameters.InfrastructureConfig.BackendConfig.StorageAccountName }}
                BackendAzureContainerName: ${{ parameters.InfrastructureConfig.BackendConfig.ContainerName }}
                BackendAzureBlobName: ${{ parameters.InfrastructureConfig.BackendConfig.BlobName }}
                WorkingDirectory: $(TerraformWorkingDirectory)
                TaskEnvironmentVariables: ${{ parameters.InfrastructureConfig.EnvironmentVariableMappings }}

            - ${{ if eq(parameters.TerraformDeployMode, 'Plan') }}:
                - template: ../tasks/terraform.yml
                  parameters:
                    Command: plan
                    EnvironmentAzureServiceConnection: ${{ parameters.InfrastructureConfig.AzureSubscriptionServiceConnection }}
                    WorkingDirectory: $(TerraformWorkingDirectory)
                    TaskEnvironmentVariables: ${{ parameters.InfrastructureConfig.EnvironmentVariableMappings }}
                    CommandOptions: '-out=$(TerraformPlanFilePath) $(VariableFilesCommandOption) -input=false'

                - template: ../tasks/powershell.yml
                  parameters:
                    TaskName: TerraformChangesCheck
                    TargetType: 'filePath'
                    ScriptFilePath: $(ScriptDirectory)/terraform/terraform_changes_check.ps1
                    FailOnStandardError: true
                    ScriptFileArguments: >
                      -VerificationMode ${{ parameters.InfrastructureConfig.VerificationMode }}
                      -TerraformPlanFilePath "$(TerraformPlanFilePath)"

            - ${{ if eq(parameters.TerraformDeployMode, 'Apply') }}:
                - template: ../tasks/terraform.yml
                  parameters:
                    Command: apply
                    EnvironmentAzureServiceConnection: ${{ parameters.InfrastructureConfig.AzureSubscriptionServiceConnection }}
                    WorkingDirectory: $(TerraformWorkingDirectory)
                    TaskEnvironmentVariables: ${{ parameters.InfrastructureConfig.EnvironmentVariableMappings }}
                    CommandOptions: '$(VariableFilesCommandOption) -input=false'

                - ${{ if parameters.InfrastructureConfig.OutputVariables }}:
                    - template: ../tasks/terraform.yml
                      parameters:
                        Command: output
                        WorkingDirectory: $(TerraformWorkingDirectory)
                        EnvironmentAzureServiceConnection: ${{ parameters.InfrastructureConfig.AzureSubscriptionServiceConnection }}
                        OutputTo: file

                    - template: ../tasks/powershell.yml
                      parameters:
                        TaskName: TerraformExportOutputsVariables
                        TargetType: 'filePath'
                        ScriptFilePath: $(ScriptDirectory)/terraform/terraform_export_outputs.ps1
                        FailOnStandardError: true
                        ScriptFileArguments: >
                          -OutputVariablesToExport $(TerraformOutputVariablesCommandOption)
                          -OutputFileName $(TerraformTask_output.jsonOutputVariablesPath)
