# Job Template: Terraform Apply
# Purpose: Runs Terraform apply to deploy infrastructure, supporting variable injection and Azure Key Vault integration.

parameters:
  # generic parameters

  - name: JobName
    type: string
    default: TerraformApply
    displayName: 'The job name for this job for ease of identity'

  - name: DependsOn
    type: object
    default: [ ]
    displayName: 'What this job will depend on'

  - name: Condition
    type: string
    default: succeeded()
    displayName: 'The condition that will control whether this job runs or not'

  - name: JobVariableMappings
    type: object
    default: { }
    displayName: "A object structure of variables to be added to the job's variables block"

  - name: TerraformArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Name for the artifact containing the terraform files for deployment'

  - name: AzDOEnvironmentName
    type: string
    displayName: 'The azure devops environment that this deployment job will be associated with'

  # key vault task parameters

  - name: KeyVaultServiceConnection
    type: string
    default: ''
    displayName: 'Service connection for key vault access secrets'

  - name: KeyVaultName
    type: string
    default: ''
    displayName: 'Name of key vault for accessing secrets'

  - name: KeyVaultSecretsFilter
    type: string
    default: '*'
    displayName: 'Filter for secrets to access from key vault'

  # terraform installer task parameters

  - name: TerraformVersion
    type: string
    default: 'latest'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  # terraform init task parameters

  - name: BackendAzureServiceConnection
    type: string
    default: ''
    displayName: 'Azure service connection for backend where the state is stored'

  - name: BackendAzureResourceGroupName
    type: string
    default: ''
    displayName: 'Azure resource group name for backend where the state is stored'

  - name: BackendAzureStorageAccountName
    type: string
    default: ''
    displayName: 'Azure storage account name for backend where the state is stored'

  - name: BackendAzureContainerName
    type: string
    default: ''
    displayName: 'Azure storage container name for backend where the state is stored'

  - name: BackendAzureBlobName
    type: string
    default: ''
    displayName: 'Azure storage blob name for backend where the state is stored'

  # terraform apply parameters

  - name: AzureSubscriptionServiceConnection
    type: string
    default: ''
    displayName: 'Azure service connection for the azdo environment'

  - name: TerraformEnvironmentVariableMappings
    type: object
    default: { }
    displayName: 'Environment variables to be passed to the task'

  - name: TerraformVariableFiles
    type: object
    default: { }
    displayName: ''

  - name: TerraformOutputVariables
    type: object
    default: { }
    displayName: ''

jobs:
  - deployment: ${{ parameters.JobName }}
    displayName: 'Terraform Apply'
    environment: ${{ parameters.AzDOEnvironmentName }}
    condition: ${{ parameters.Condition }}
    dependsOn: ${{ parameters.DependsOn }}
    variables:
      - template: ../utils/concat_list.yml
        parameters:
          Items: ${{ parameters.TerraformVariableFiles }}
          Prefix: ' -var-file="'
          Suffix: '"'
          OutputVariableName: TerraformVariableFilesCommandOption
      - name: TerraformOutputFile
        value: $(Pipeline.Workspace)/terraform_outputs.json
      - name: TerraformWorkingDirectory
        value: $(Pipeline.Workspace)/${{ parameters.TerraformArtifactName }}
      - ${{ each JobVariableMapping in parameters.JobVariableMappings }}:
          - ${{ if or(eq(JobVariableMapping.Key, 'group'), eq(JobVariableMapping.Key, 'template')) }}:
              - ${{ JobVariableMapping.Key }}: ${{ JobVariableMapping.Value }}
          - ${{ else }}:
              - name: ${{ JobVariableMapping.Key }}
                value: ${{ JobVariableMapping.Value }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../tasks/download_pipeline_artifact.yml
              parameters:
                ArtifactName: ${{ parameters.TerraformArtifactName }}

            - template: ../tasks/terraform_installer.yml
              parameters:
                TerraformVersion: ${{ parameters.TerraformVersion }}

            - ${{ if and(parameters.KeyVaultServiceConnection, parameters.KeyVaultName, parameters.KeyVaultSecretsFilter) }}:
                - template: ../tasks/azure_key_vault.yml
                  parameters:
                    KeyVaultServiceConnection: ${{ parameters.KeyVaultServiceConnection }}
                    KeyVaultName: ${{ parameters.KeyVaultName }}
                    SecretsFilter: ${{ parameters.KeyVaultSecretsFilter }}

            - template: ../tasks/terraform.yml
              parameters:
                Command: init
                BackendAzureServiceConnection: ${{ parameters.BackendAzureServiceConnection }}
                BackendAzureResourceGroupName: ${{ parameters.BackendAzureResourceGroupName }}
                BackendAzureStorageAccountName: ${{ parameters.BackendAzureStorageAccountName }}
                BackendAzureContainerName: ${{ parameters.BackendAzureContainerName }}
                BackendAzureBlobName: ${{ parameters.BackendAzureBlobName }}
                WorkingDirectory: $(TerraformWorkingDirectory)
                TaskEnvironmentVariables: ${{ parameters.TerraformEnvironmentVariableMappings }}

            - template: ../tasks/terraform.yml
              parameters:
                Command: apply
                EnvironmentAzureServiceConnection: ${{ parameters.AzureSubscriptionServiceConnection }}
                WorkingDirectory: $(TerraformWorkingDirectory)
                TaskEnvironmentVariables: ${{ parameters.TerraformEnvironmentVariableMappings }}
                CommandOptions: '$(TerraformVariableFilesCommandOption) -input=false'

            - template: ../tasks/terraform.yml
              parameters:
                Command: output
                WorkingDirectory: $(TerraformWorkingDirectory)
                EnvironmentAzureServiceConnection: ${{ parameters.AzureSubscriptionServiceConnection }}
                OutputTo: file
                OutputFileName: $(TerraformOutputFile)
                OutputFormat: json

            - ${{ if parameters.TerraformOutputVariables }}:
              - template: ../tasks/powershell.yml
                parameters:
                  TaskName: TerraformExportOutputsVariables
                  TargetType: 'filePath'
                  ScriptFilePath: $(ScriptDirectory)/terraform/terraform_export_outputs.ps1
                  FailOnStandardError: true
                  ScriptFileArguments: >
                    -TerraformOutputVariables ${{ parameters.TerraformOutputVariables }}
                    -OutputFileName $(TerraformOutputFile)
