variables:
  - group: Experimental-VariablesAndScope-ForPipeline
  - template: PipelineVariableTemplate.yml
  - name: PipelineVariable
    value: PipelineVariableValue

stages:
  - stage:
    variables:
      - group: Experimental-VariablesAndScope-ForStage
      - template: StageVariableTemplate.yml
      - name: StageVariable
        value: StageVariableValue
    jobs:
      - job:
        variables:
          - group: Experimental-VariablesAndScope-ForJob
          - template: JobVariableTemplate.yml
          - name: JobVariable
            value: JobVariableValue
        steps:
          - script: |
              echo "All of the Template Variables"
              echo "TemplateVariableForPipeline at compile time: '${{ variables.TemplateVariableForPipeline }}'"
              echo "TemplateVariableForStage at compile time: '${{ variables.TemplateVariableForStage }}'"
              echo "TemplateVariableForJob at compile time: '${{ variables.TemplateVariableForJob }}'"
              echo "TemplateVariableForPipeline at runtime: '$(TemplateVariableForPipeline)'"
              echo "TemplateVariableForStage at runtime: '$(TemplateVariableForStage)'"
              echo "TemplateVariableForJob at runtime: '$(TemplateVariableForJob)'"
              echo "All of the Library Variable Group Variables"
              echo "NonSecretVariable for Pipeline at runtime: '$(nonSecretVariable-ForPipeline)'"
              echo "NonSecretVariable for Stage at runtime: '$(nonSecretVariable-ForStage)'"
              echo "NonSecretVariable for Job at runtime: '$(nonSecretVariable-ForJob)'"
              echo "All of the Normal Variables"
              echo "PipelineVariable at compile time: '${{ variables.PipelineVariable }}'"
              echo "StageVariable at compile time: '${{ variables.StageVariable }}'"
              echo "JobVariable at compile time: '${{ variables.JobVariable }}'"
              echo "PipelineVariable at runtime: '$(PipelineVariable)'"
              echo "StageVariable at runtime: '$(StageVariable)'"
              echo "JobVariable at runtime: '$(JobVariable)'"
