parameters:
  - name: ArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Artifact Name for Target Path to be saved as.'

  - name: RelativePathToTerraformFiles
    type: string
    displayName: "Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact."

  - name: TerraformVersion
    type: string
    default: 'latest'
    displayName: "Version of Terraform CLI tool to use with the terraform files."

  - name: TerraformBuildInjectionSteps
    type: stepList
    default: []
    displayName: "Steps to be carried out before the terraform is init, validated, and packaged."

stages:
  - stage: Build
    displayName: "Build"
    jobs:
      - template: ../jobs/terraform_build.yml
        parameters:
          ArtifactName: ${{ parameters.ArtifactName }}
          RelativePathToTerraformFiles: ${{ parameters.RelativePathToTerraformFiles }}
          TerraformVersion: ${{ parameters.TerraformVersion }}
          TerraformBuildInjectionSteps: ${{ parameters.TerraformBuildInjectionSteps }}
