parameters:
  - name: EnvironmentConfig
    type: object
    # NO default - Consumer must provide this
    displayName: ''

  - name: TerraformArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Name for the artifact containing the terraform files for deployment'

  - name: RunPlanOnly
    type: boolean
    default: false
    displayName: 'Whether only the terraform plan should be ran and no deployment made'

  - name: TerraformVersion
    type: string
    default: '1.14.x'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

stages:
  - stage: Deploy_${{ parameters.EnvironmentConfig.Name }}_Infrastructure
    displayName: 'Deploy ${{ parameters.EnvironmentConfig.Name }}'

    ${{ if or(not(parameters.EnvironmentConfig.Stage.DependsOn), eq(parameters.EnvironmentConfig.Stage.DependsOn, '')) }}:
      "environment '${{ parameters.EnvironmentConfig.Name }}' DependsOn is not properly defined and is a required field.": "Error"
    dependsOn: ${{ parameters.EnvironmentConfig.Stage.DependsOn }}
    ${{ if or(not(parameters.EnvironmentConfig.Stage.Condition), eq(parameters.EnvironmentConfig.Stage.Condition, '')) }}:
      "environment '${{ parameters.EnvironmentConfig.Name }}' Condition is not properly defined and is a required field.": "Error"
    condition: ${{ parameters.EnvironmentConfig.Stage.Condition }}

    jobs:
      - template: ../jobs/terraform_plan_verify_apply_jobList.yml
        parameters:
          TerraformVersion: ${{ parameters.TerraformVersion }}
          TerraformArtifactName: ${{ parameters.TerraformArtifactName }}
          RunPlanOnly: ${{ parameters.RunPlanOnly }}
          EnvironmentName: ${{ parameters.EnvironmentConfig.Name }}
          InfrastructureConfig: ${{ parameters.EnvironmentConfig.InfrastructureConfig }}
